///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String fontsPoppinsRegular = 'assets/fonts/Poppins-Regular.ttf';
  static const String imagesAppleIcon = 'assets/images/Apple_Icon.svg';
  static const String imagesFacebokIcon = 'assets/images/Facebok_Icon.svg';
  static const String imagesFrame = 'assets/images/Frame.svg';
  static const String imagesGoogleIcon = 'assets/images/Google_Icon.svg';
  static const String imagesIllustrationCartEmpty = 'assets/images/Illustration_Cart_Empty.svg';
  static const String imagesIllustrationCongratulations = 'assets/images/Illustration_Congratulations.svg';
  static const String imagesIllustrationCreateNewPassword = 'assets/images/Illustration_Create_New_Password.svg';
  static const String imagesIllustrationForgotPasswordWithEmail = 'assets/images/Illustration_Forgot_Password_With_Email.svg';
  static const String imagesIllustrationForgotPasswordWithPhone = 'assets/images/Illustration_Forgot_Password_With_Phone.svg';
  static const String imagesIllustrationLogInValidation = 'assets/images/Illustration_Log_In_Validation.svg';
  static const String imagesIllustrationOnboarding2 = 'assets/images/Illustration_Onboarding_2.svg';
  static const String imagesIllustrationOnboarding3 = 'assets/images/Illustration_Onboarding_3.svg';
  static const String imagesIllustrationSearchNotFound = 'assets/images/Illustration_Search_Not_Found.svg';
  static const String imagesIllustrationSuccessOrder = 'assets/images/Illustration_Success_Order.svg';
  static const String imagesIllustrationVerificationCodeWithEmail = 'assets/images/Illustration_Verification_Code_With_Email.svg';
  static const String imagesIllustrationVerificationCodeWithPhone = 'assets/images/Illustration_Verification_Code_With_Phone.svg';
  static const String imagesOffer1 = 'assets/images/Offer_1.png';
  static const String imagesSmartWatch = 'assets/images/Smart_Watch.png';
  static const String imagesSearchIconsUIA = 'assets/images/Search_Icons_UIA.png';
  static const String imagesWarning = 'assets/images/warning.png';
  static const String imagesPhone = 'assets/images/Phone.png';
  static const String imagesLogoLogIn = 'assets/images/Logo_Log_In.png';



}
